// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: Icon
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "spacing": {
        "icon-global-md-size": "24px",
        "icon-global-md-stroke": "2px",
        "icon-global-sm-size": "16px",
        "icon-global-sm-stroke": "1.6px"
      }
    },
  },
};
