// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis • component: MenuItem
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "menu-item-global-container-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "menu-item-global-container-hover": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "menu-item-global-container-idle": "light-dark(transparent, transparent)"
      },
      "textColor": {
        "menu-item-link-description-false-label-active": "light-dark(rgb(23 99 207), rgb(117 174 240))",
        "menu-item-link-description-false-label-hover": "light-dark(rgb(23 99 207), rgb(117 174 240))",
        "menu-item-link-description-false-label-idle": "light-dark(rgb(23 99 207), rgb(117 174 240))",
        "menu-item-link-description-true-description-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-link-description-true-description-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-link-description-true-description-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-link-description-true-label-active": "light-dark(rgb(23 99 207), rgb(117 174 240))",
        "menu-item-link-description-true-label-hover": "light-dark(rgb(23 99 207), rgb(117 174 240))",
        "menu-item-link-description-true-label-idle": "light-dark(rgb(23 99 207), rgb(117 174 240))",
        "menu-item-static-description-false-label-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-false-label-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-false-label-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-true-description-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-true-description-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-true-description-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-true-label-active": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-true-label-hover": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-true-label-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "fill": {
        "menu-item-global-icon-active": "light-dark(rgb(23 99 207), rgb(117 174 240))",
        "menu-item-global-icon-hover": "light-dark(rgb(23 99 207), rgb(117 174 240))",
        "menu-item-global-icon-idle": "light-dark(rgb(23 99 207), rgb(117 174 240))"
      },
      "ringColor": {
        "menu-item-link-description-false-label-focus": "light-dark(rgb(23 99 207), rgb(117 174 240))",
        "menu-item-link-description-true-description-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-link-description-true-label-focus": "light-dark(rgb(23 99 207), rgb(117 174 240))",
        "menu-item-link-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-false-label-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-true-description-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-description-true-label-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-static-focus": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "menu-item-global-container-focus": "light-dark(rgb(190 215 244), rgb(11 66 142))",
        "menu-item-global-icon-focus": "light-dark(rgb(23 99 207), rgb(117 174 240))"
      },
      "fontFamily": {
        "menu-item-link-description-false-label-text-style": "Inter, system-ui, sans-serif",
        "menu-item-link-description-true-description-text-style": "Inter, system-ui, sans-serif",
        "menu-item-link-description-true-label-text-style": "Inter, system-ui, sans-serif",
        "menu-item-static-description-false-label-text-style": "Inter, system-ui, sans-serif",
        "menu-item-static-description-true-description-text-style": "Inter, system-ui, sans-serif",
        "menu-item-static-description-true-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "menu-item-link-description-false-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ],
        "menu-item-link-description-true-description-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "menu-item-link-description-true-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ],
        "menu-item-static-description-false-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "menu-item-static-description-true-description-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "menu-item-static-description-true-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "500"
          }
        ]
      },
      "spacing": {
        "menu-item-global-container-gap": "8px",
        "menu-item-global-container-height-description-min": "56px",
        "menu-item-global-container-height-min": "40px",
        "menu-item-global-container-padding-x": "16px",
        "menu-item-global-container-padding-y": "8px",
        "menu-item-global-container-width-min": "128px",
        "menu-item-global-container-content-gap": "0px",
        "menu-item-global-container-left-padding-y": "4px",
        "menu-item-global-icon-size": "16px"
      }
    },
  },
};
