// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis-dark-mode • component: Table
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "table-table-data-container-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "table-table-data-container-hover": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "table-table-data-container-idle": "light-dark(transparent, transparent)",
        "table-table-header-container-active": "light-dark(rgb(214 228 245), rgb(48 50 54))",
        "table-table-header-container-hover": "light-dark(rgb(238 242 247), rgb(46 47 50))",
        "table-table-header-container-idle": "light-dark(transparent, transparent)"
      },
      "textColor": {
        "table-table-data-value-disabled": "light-dark(rgb(175 178 182), rgb(85 89 94))",
        "table-table-data-value-idle": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "table-table-header-label": "light-dark(rgb(24 25 27), rgb(244 245 245))"
      },
      "borderColor": {
        "table-global-container-border-color": "light-dark(rgb(214 228 245), rgb(48 50 54))"
      },
      "fontFamily": {
        "table-table-data-value-text-style": "Inter, system-ui, sans-serif",
        "table-table-header-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "table-table-data-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "table-table-header-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "table-global-container-border-width": "1px",
        "table-global-container-height": "40px",
        "table-global-container-padding-x": "16px",
        "table-global-container-padding-y": "8px",
        "table-table-data-gap": "8px",
        "table-table-header-gap": "8px",
        "table-table-header-sort-icon-size": "16px"
      }
    },
  },
};
