// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: acronis-dark-mode • component: Tag
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "tag-ai-container": "light-dark(rgb(249 245 251), rgb(62 15 62))",
        "tag-critical-container": "light-dark(rgb(255 249 245), rgb(51 23 0))",
        "tag-danger-container": "light-dark(rgb(254 246 246), rgb(62 15 15))",
        "tag-info-container": "light-dark(rgb(0 32 77), rgb(0 32 77))",
        "tag-neutral-container": "light-dark(rgb(244 245 245), rgb(24 25 27))",
        "tag-success-container": "light-dark(rgb(248 252 249), rgb(2 44 13))",
        "tag-warning-container": "light-dark(rgb(255 252 240), rgb(61 44 0))"
      },
      "textColor": {
        "tag-ai-label": "light-dark(rgb(130 23 130), rgb(250 209 250))",
        "tag-critical-label": "light-dark(rgb(77 34 0), rgb(253 159 99))",
        "tag-danger-label": "light-dark(rgb(195 34 34), rgb(244 154 154))",
        "tag-info-label": "light-dark(rgb(190 215 244), rgb(190 215 244))",
        "tag-neutral-label": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "tag-success-label": "light-dark(rgb(2 44 13), rgb(132 199 105))",
        "tag-warning-label": "light-dark(rgb(204 146 0), rgb(255 210 61))"
      },
      "borderColor": {
        "tag-critical-container-border-color": "light-dark(rgb(128 57 0), rgb(215 120 37))",
        "tag-danger-container-border-color": "light-dark(rgb(217 38 38), rgb(237 94 94))",
        "tag-info-container-border-color": "light-dark(rgb(117 174 240), rgb(117 174 240))",
        "tag-neutral-container-border-color": "light-dark(rgb(48 50 54), rgb(138 145 160))",
        "tag-success-container-border-color": "light-dark(rgb(8 69 23), rgb(74 163 75))",
        "tag-warning-container-border-color": "light-dark(rgb(245 184 0), rgb(245 184 0))"
      },
      "fill": {
        "tag-ai-icon": "light-dark(rgb(130 23 130), rgb(250 209 250))",
        "tag-critical-icon": "light-dark(rgb(77 34 0), rgb(253 159 99))",
        "tag-danger-icon": "light-dark(rgb(195 34 34), rgb(244 154 154))",
        "tag-info-icon": "light-dark(rgb(190 215 244), rgb(190 215 244))",
        "tag-neutral-icon": "light-dark(rgb(24 25 27), rgb(244 245 245))",
        "tag-success-icon": "light-dark(rgb(2 44 13), rgb(132 199 105))",
        "tag-warning-icon": "light-dark(rgb(204 146 0), rgb(255 210 61))"
      },
      "fontFamily": {
        "tag-global-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "tag-global-label-text-style": [
          "12px",
          {
            "lineHeight": "16px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "tag-global-container-border-width": "1px",
        "tag-global-container-gap": "4px",
        "tag-global-container-padding-x": "8px",
        "tag-global-container-padding-y": "0px",
        "tag-global-container-width-max": "256px",
        "tag-global-container-width-min": "32px",
        "tag-global-md-container-height": "24px",
        "tag-global-md-icon-border-width": "1.6px",
        "tag-global-md-icon-size": "16px",
        "tag-global-sm-container-height": "20px"
      },
      "borderRadius": {
        "tag-global-container-border-radius": "999px"
      }
    },
  },
};
