// Generated by @acronis-platform/style-dictionary — DO NOT EDIT.
// Source: @acronis-platform/design-tokens • brand: deep-sky • component: Table
// Tailwind preset (baked token values) — consume via `@config`.

export default {
  theme: {
    extend: {
      "backgroundColor": {
        "table-table-data-container-active": "light-dark(rgb(216 222 228), rgb(216 222 228))",
        "table-table-data-container-hover": "light-dark(rgb(236 238 239), rgb(236 238 239))",
        "table-table-data-container-idle": "light-dark(transparent, transparent)",
        "table-table-header-container-active": "light-dark(rgb(216 222 228), rgb(216 222 228))",
        "table-table-header-container-hover": "light-dark(rgb(236 238 239), rgb(236 238 239))",
        "table-table-header-container-idle": "light-dark(transparent, transparent)"
      },
      "textColor": {
        "table-table-data-value-disabled": "light-dark(rgb(41 49 55), rgb(41 49 55))",
        "table-table-data-value-idle": "light-dark(rgb(68 81 93), rgb(68 81 93))",
        "table-table-header-label": "light-dark(rgb(68 81 93), rgb(68 81 93))"
      },
      "borderColor": {
        "table-global-container-border-color": "light-dark(rgb(199 203 207), rgb(199 203 207))"
      },
      "fontFamily": {
        "table-table-data-value-text-style": "Inter, system-ui, sans-serif",
        "table-table-header-label-text-style": "Inter, system-ui, sans-serif"
      },
      "fontSize": {
        "table-table-data-value-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "400"
          }
        ],
        "table-table-header-label-text-style": [
          "14px",
          {
            "lineHeight": "24px",
            "letterSpacing": "0px",
            "fontWeight": "600"
          }
        ]
      },
      "spacing": {
        "table-global-container-border-width": "1px",
        "table-global-container-height": "40px",
        "table-global-container-padding-x": "16px",
        "table-global-container-padding-y": "8px",
        "table-table-data-gap": "8px",
        "table-table-header-gap": "8px",
        "table-table-header-sort-icon-size": "16px"
      }
    },
  },
};
